---
# Name the file secrets.yml

development:
  GITHUB_TOKEN: <personal access token for github api>

test:
  GITHUB_TOKEN: <personal access token for github api>

production:
  GITHUB_TOKEN: <personal access token for github api>