---
# Name the file secrets.yml

development:
  GITHUB_TOKEN: <personal access token for github api>
  SESSION_SECRET: <some secret>

test:
  GITHUB_TOKEN: <personal access token for github api>
  SESSION_SECRET: <some secret>

production:
  GITHUB_TOKEN: <personal access token for github api>
  SESSION_SECRET: <some secret>